version: "3.9"

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "TuPassword123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - corebanking-network

  customerservice:
    build:
      context: .
      dockerfile: CustomerService.API/Dockerfile
    ports:
      - "5002:8080"
    environment:
     - ASPNETCORE_ENVIRONMENT=Docker
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=CustomerDb;User Id=sa;Password=TuPassword123!;TrustServerCertificate=True
    depends_on:
      - sqlserver
    networks:
      - corebanking-network

  accountservice:
    build:
      context: .
      dockerfile: AccountService.API/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=AccountDb;User Id=sa;Password=TuPassword123!;TrustServerCertificate=True
      - Services__CustomerService=http://customerservice:8080
    depends_on:
      - sqlserver
      - customerservice
    networks:
      - corebanking-network

networks:
  corebanking-network:
    driver: bridge