
services:

  accountservice:
    build:
      context: .
      dockerfile: AccountService.API/Dockerfile

    container_name: accountservice

    ports:
      - "5001:8080"

    networks:
      - banking-network

    environment:
      ASPNETCORE_ENVIRONMENT: "Development"

      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=AccountDb;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True"

  customerservice:
    build:
      context: .
      dockerfile: CustomerService.API/Dockerfile

    container_name: customerservice

    ports:
      - "5002:8080"

    networks:
      - banking-network

    environment:
      ASPNETCORE_ENVIRONMENT: "Development"

      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=CustomerDb;Username=postgres;Password=postgres"

networks:
  banking-network:
    external: true