name: cbank

services:
  customerservice:
    build:
      context: ../..
      dockerfile: CustomerService.API/Dockerfile

    ports:
      - "5002:8080"

    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=CustomerDb;User Id=sa;Password=TuPassword123!;TrustServerCertificate=True

    networks:
      -  banking-network

  accountservice:
    build:
      context: ../..
      dockerfile: AccountService.API/Dockerfile

    ports:
      - "5001:8080"

    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=AccountDb;User Id=sa;Password=TuPassword123!;TrustServerCertificate=True
      - Services__CustomerService=http://customerservice:8080

    depends_on:
      - customerservice

    networks:
      -  banking-network

networks:
   banking-network:
    driver: bridge